### ISSUE TITLE
Nearly $400/month or $20/day to run this minimal test - which isn't obvious

### ISSUE THREAD

**Issue by rib** [Laremere/space-agon#1]
> gcloud container clusters create space-agon --cluster-version=1.12 \
  --tags=game-server \
  --scopes=gke-default \
  --num-nodes=4 \
  --no-enable-autoupgrade \
  --machine-type=n1-standard-4

The cost of one n1-normal-4 machine is nearly $100/month (with discounts), and even though it's more likely to be run briefly for a test, if you forgot to shut it down for one day that would still cost around $20 for one day (no discount). Someone not very familiar yet with the costs involved might not think twice about this.

I was recently surprised after following some of the examples for Agones/Open Match that it cost me around $40 just because I left some things running over night. I've only recently started using google cloud platform (have used EC2 more beforehand) and just assumed the demos/examples would be done on cheap configurations.

I think it could be worth warning about the cost and/or perhaps recommending a smaller, lower-end cluster for testing (`--num-nodes=1` and `--machine-type=n1-standard-1/2` is probably enough)

**Comment by Laremere** [comment]
Hey, I haven't yet spent the effort on finding the right size for this project.  For now I've added a warning.

Thanks for your feedback.

**Comment by rib** [comment]
Yeah, np. I just tried dropping it down to n1-normal-n2 num-nodes=1 but for reference that wasn't enough since it refused to schedule the 'dedicated' servers. Even if I droped the requested cpu resources to 100m instead of 500m that didn't seem to work either. Was just going to try n1-normal-n1 and num-nodes=3 for now.

Thanks
